package net.celloscope.mraims.loanportfolio.core.util.enums;

import lombok.Getter;

@Getter
public enum Constants {
    ACCOUNT_TYPE_LOAN("Loan"),
    ACCOUNT_TYPE_SAVINGS("Savings"),
    TRANSACTION_CODE_LOAN_REPAY("LOAN_REPAY"),
    TRANSACTION_CODE_LOAN_REPAY_PRIN("LOAN_REPAY_PRIN"),
    TRANSACTION_CODE_LOAN_REPAY_SC("LOAN_REPAY_SC"),
    TRANSACTION_CODE_SAVINGS_WITHDRAW("SAVINGS_WITHDRAW"),
    TRANSACTION_CODE_SAVINGS_DEPOSIT("SAVINGS_DEPOSIT"),
    TRANSACTION_CODE_INTEREST_DEPOSIT("INTEREST_DEPOSIT"),
    TRANSACTION_CODE_LOAN_DISBURSEMENT("LOAN_DISBURSEMENT"),
    TRANSACTION_CODE_LOAN_ADJUSTMENT("LOAN_ADJUSTMENT"),

    TRANSACTION_CODE_REVERSE_LOAN_REPAY("REVERSE_LOAN_REPAY"),
    TRANSACTION_CODE_REVERSE_SAVINGS_DEPOSIT("REVERSE_SAVINGS_DEPOSIT"),
    TRANSACTION_CODE_REVERSE_SAVINGS_WITHDRAW("REVERSE_SAVINGS_WITHDRAW"),

    TRANSACTION_CODE_ADJUSTMENT_LOAN_REPAY("ADJUSTMENT_LOAN_REPAY"),
    TRANSACTION_CODE_ADJUSTMENT_SAVINGS_DEPOSIT("ADJUSTMENT_SAVINGS_DEPOSIT"),
    TRANSACTION_CODE_ADJUSTMENT_SAVINGS_WITHDRAW("ADJUSTMENT_SAVINGS_WITHDRAW"),

    SAVINGS_TRANSACTION_ADJUSTMENT_TYPE_DEPOSIT("DEPOSIT"),
    SAVINGS_TRANSACTION_ADJUSTMENT_TYPE_WITHDRAW("WITHDRAW"),

    CLOSING_TYPE_JUNE_CLOSING("JUNE_CLOSING"),
    CLOSING_TYPE_YEAR_CLOSING("YEAR_CLOSING"),

    PAYMENT_MODE_CASH("CASH"),
    PAYMENT_MODE_BANK("BANK"),
    PAYMENT_MODE_REBATE("REBATE"),
    CALCULATION_META_PROPERTY("Calculation Meta-Property"),

    TRANSACTION_CODE_FDR_CLOSURE("FDR_CLOSURE"),
    TRANSACTION_CODE_DPS_CLOSURE("DPS_CLOSURE"),

    DEPOSIT_TERM_PERIOD_YEAR("Year"),
    DEPOSIT_TERM_PERIOD_MONTH("Month"),

    COLLECTION_TYPE_CASH("Cash"),
    COLLECTION_TYPE_ADJUSTMENT("Adjustment"),
    COLLECTION_TYPE_COMBINE("Combine"),
    COLLECTION_TYPE_TRANSACTION_ADJUSTMENT_LOAN("Loan"),
    COLLECTION_TYPE_TRANSACTION_ADJUSTMENT_DEPOSIT("Deposit"),
    COLLECTION_TYPE_TRANSACTION_ADJUSTMENT_WITHDRAW("Withdraw"),
    JOURNAL_ENTRY_TYPE_IN("IN"),
    JOURNAL_ENTRY_TYPE_OUT("OUT"),

    TRANSACTION_CODE_LOAN_REBATE("LOAN_REBATE"),

    SOURCE_APPLICATION("Application"),
    SOURCE_MIGRATION("Migration");

    private final String value;

    Constants(String value) {
        this.value = value;
    }
}
