package net.celloscope.mraims.loanportfolio.features.autovoucher.domain;

import lombok.Getter;

@Getter
public enum AutoVoucherEnum {
    VOUCHER_NAME_PAYMENT_VOUCHER("Payment Voucher"),
    VOUCHER_NAME_RECEIVED_VOUCHER("Received Voucher"),
    VOUCHER_NAME_ADJUSTMENT_VOUCHER("Adjustment Voucher"),
    VOUCHER_NAME_SC_PROVISION_VOUCHER("Service Charge Provision Voucher"),
    VOUCHER_NAME_FEE_COLLECTION_VOUCHER("Fee Collection Voucher"),
    VOUCHER_NAME_REVERSE_LOAN_REPAY_VOUCHER("Reverse Loan Repay Voucher"),
    VOUCHER_NAME_ADJUSTMENT_LOAN_REPAY_VOUCHER("Adjustment Loan Repay Voucher"),
    VOUCHER_NAME_REVERSE_SAVINGS_DEPOSIT_VOUCHER("Reverse Savings Deposit Voucher"),
    VOUCHER_NAME_ADJUSTMENT_SAVINGS_DEPOSIT_VOUCHER("Adjustment Savings Deposit Voucher"),
    VOUCHER_NAME_REVERSE_SAVINGS_WITHDRAW_VOUCHER("Reverse Savings Withdraw Voucher"),
    VOUCHER_NAME_ADJUSTMENT_SAVINGS_WITHDRAW_VOUCHER("Adjustment Savings Withdraw Voucher"),

    VISIBLE_YES("Yes"),
    VISIBLE_NO("No"),

    JOURNAL_PROCESS_AUTO("Auto"),

    VOUCHER_ID_PREFIX_PAYMENT_VOUCHER("PV"),
    VOUCHER_ID_PREFIX_RECEIVED_VOUCHER("RV"),
    VOUCHER_ID_PREFIX_ADJUSTMENT_VOUCHER("AV"),
    VOUCHER_ID_PREFIX_SC_PROVISION_VOUCHER("SPV"),
    VOUCHER_ID_PREFIX_UNLISTED_VOUCHER("V"),
    VOUCHER_ID_PREFIX_FEE_COLLECTION_VOUCHER("FC"),
    VOUCHER_ID_PREFIX_REVERSE_LOAN_REPAY_VOUCHER("RLR"),
    VOUCHER_ID_PREFIX_ADJUSTMENT_LOAN_REPAY_VOUCHER("ALR"),
    VOUCHER_ID_PREFIX_REVERSE_SAVINGS_DEPOSIT_VOUCHER("RSD"),
    VOUCHER_ID_PREFIX_ADJUSTMENT_SAVINGS_DEPOSIT_VOUCHER("ASD"),
    VOUCHER_ID_PREFIX_REVERSE_SAVINGS_WITHDRAW_VOUCHER("RSW"),
    VOUCHER_ID_PREFIX_ADJUSTMENT_SAVINGS_WITHDRAW_VOUCHER("ASW"),

    ;
    private final String value;

    AutoVoucherEnum(String value) {
        this.value = value;
    }
}
